### ISSUE TITLE
Installation on OSX 10.9.4 fails with "/usr/local/bin/gawk: Bad CPU type in executable" 

### ISSUE THREAD

**Issue by MarcPerlman** [humdrum-tools/humdrum#3]
Even though I created /etc/profile.d/humdrum.sh as instructed, the shell variables are not getting assigned the values listed in humdrum.sh; in particular, AWK_VER = gawk  

Also, even though I installed into ~/humdrum-tools, no ~/humdrum-tools/humextra/bin directory was built.  (Though this probably is a separate issue unrelated to the "Bad CPU type in executable" message.)

**Comment by craigsapp** [comment]
This is probably too old now to be relevant, but I will answer in case someone else has the same questions.  I didn't notice it because I blissfully don't seem to be getting email notices for this issue list...

**1. /etc/profile.d/humdrum.sh not doing anything**

Most versions of linux use /etc/profile.d system, Apple OS X does not.  It is better to fix OS X so that is does the same, since it is easier to maintain various shell settings without altering /etc/profile each time.  Add the following lines of code to /etc/profile (using the command `sudo vi /etc/profile` if you are not root, or `sudo nano /etc/profile` if you do not have enough brain cells to use a real editor :-)

```
for sh in /etc/profile.d/*.sh ; do
        [ -r "$sh" ] && . "$sh"
done
unset sh
```

Then log out and in again. The settings in /etc/profile.d should now be read (or you can type `. /etc/profile` in the same terminal session without the need to login.

In any case, I set up the Humdrum Toolkit at https://github.com/humdrum-tools to not require environmental variables such as AWK_VER.  The scripts now will search for the most obvious versions of awk that they can find if that variable is not set.

**2. No humextra/bin directory was built**

Perhaps you were installing before I put instructions into the https://github.com/humdrum-tools/humdrum-tools repository or the makefile was not the same as it should be now.  To create the files in ~/humdrum-tools/humextra/bin, either of these command sequences should work:

```
git clone --recursive https://github.com/humdrum-tools/humdrum-tools
cd humdrum-tools
make
```

or to compile humextra programs without installing standard Humdrum Toolkit programs:

```
git clone --recursive https://github.com/humdrum-tools/humdrum-tools
cd humdrum-tools
cd humextra
make
```

or just humextras installed by itself:

```
git clone https://github.com/craigsapp/humextra
cd humextra
make
```

In OS X, this assumes that you have Xcode installed and/or the command-line tools (which are not installed by default).  in OS X 10.9 and higher, they are easy to install https://coderwall.com/p/yzj_gq/installing-xcode-command-line-tools-on-os-x-mavericks

```
xcode-select --install
```

In OS X 10.8 and less, the procedure is more involved.  The problem was that downloading with `git clone` does not include the compiling stage, so you have to type `cd humdrum-tools; make` to finish the installation (plus some $PATH setting mentioned by the makefile(s)). And running make requires gcc (or the clang equivalent in OS X) to compile the programs created in the bin directory, so the `xcode-select --install` command may have to be run first if you haven't compiled things in OS X before.
